### ISSUE TITLE
Co-authored-by does not template correctly with `-v` flag on git commit.

### ISSUE THREAD

**Issue by dewyze** [git-duet/git-duet#63] opened 2018-04-18 19:18 UTC
When I run `git commit` with the Co-authored-by feature enabled, it works great! (Thanks, btw).

However, when I run it with `git commit -v` and verbose mode enabled, it places the `Co-authored-by` below the verbose stuff:

```
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch git_duet_co_authored_by
# Your branch is up-to-date with 'origin/git_duet_co_authored_by'.
#
# Changes to be committed:
#       new file:   banana
#
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
diff --git a/banana b/banana
new file mode 100644
index 0000000..e69de29

Co-authored-by: Foo Bar <foo.bar@example.com>
```

And thus it is not actually included in the commit.

**Comment by ansd** [comment] 2018-04-19 00:52
@dewyze, this is strange. It actually works fine for me:
```


Co-authored-by: David Ansari <david.ansari@sap.com>
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
# Changes to be committed:
#       new file:   c
#
# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.
diff --git a/c b/c
new file mode 100644
index 0000000..e69de29
```

[This commit](https://github.com/git-duet/git-duet/commit/07a63cb8e6dbb1b98f990afd6feb1817ce7f4bc0) should have fixed the problem you described above because `git interpret-trailers` makes sure that the trailer appears before the verbose stuff.

**Comment by jszwedko** [comment] 2018-04-20 15:55
Hmm, I'm also unable to reproduce this, what do you see with `git-duet -v` @dewyze ?

Also, is it possible to share more of your `.gitconfig`? Maybe there is something in there that is affecting behavior.

**Comment by dewyze** [comment] 2018-04-20 18:39
Some more data I can provide:

Git version: 2.11.0

Also, this only happens with git commit, not git dci. Even though GIT_DUET_GLOBAL=true in the env.

**Comment by jszwedko** [comment] 2018-04-20 19:15
Thanks @dewyze !

It does look like this is an issue that was fixed in git 2.14.0 (https://github.com/git/git/blob/master/Documentation/RelNotes/2.14.0.txt#L347-L351). Is it possible to upgrade your version of git?

We should add this gotcha to the README in case others run into it.

**Comment by dewyze** [comment] 2018-04-27 20:42
We can try and upgrade git, but at least knowing the problem is sufficient. You can close this Issues if you think it's done.

**Comment by jszwedko** [comment] 2018-04-29 23:39
Added a note in 30b377e. Thanks again for the report.

**Closed as completed by jszwedko** 2018-04-29 23:39 UTC
